/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/xbot.glb 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useControls } from 'leva'
import { useDispatch } from 'react-redux'
import { getAnimation } from '@/redux/animationReducer'
import MidiControl from '@/webmidi/webmidiTest'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/xbot.glb')
  const { actions, names } = useAnimations(animations, group)
  console.log(names)


  // MidiControl.addAbletonListener('noteon', console.log('hello'), 1, 'controlSkeleton')
  
  // model animation
  useEffect(()=>{
    actions[names[3]].reset().fadeIn(0.5).play()
    
  }, [])

  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Beta_Joints" geometry={nodes.Beta_Joints.geometry} material={materials.Beta_Joints_MAT} skeleton={nodes.Beta_Joints.skeleton} />
          <skinnedMesh name="Beta_Surface" geometry={nodes.Beta_Surface.geometry} material={materials['asdf1:Beta_HighLimbsGeoSG2']} skeleton={nodes.Beta_Surface.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/xbot.glb')
